# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['image']},
        ),
    ]
